//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : UserData
	/// Data Source    : UserData
	/// Server Version : 3.24.0
	/// </summary>
	public partial class UserDataDB : LinqToDB.Data.DataConnection
	{
		public ITable<User> Users { get { return this.GetTable<User>(); } }

		public UserDataDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public UserDataDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("Users")]
	public partial class User
	{
		[Column("role"),         Nullable] public string Role         { get; set; } // string(max)
		[Column("name"),         Nullable] public string Name         { get; set; } // string(max)
		[Column("account"),      Nullable] public string Account      { get; set; } // string(max)
		[Column("password"),     Nullable] public string Password     { get; set; } // string(max)
		[Column("emailAddress"), Nullable] public string EmailAddress { get; set; } // string(max)
		[Column("camp"),         Nullable] public string Camp         { get; set; } // string(max)
	}
}

#pragma warning restore 1591
